# Generated by Django 5.0.1 on 2024-04-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0002_trieda_alter_student_trieda_alter_ucitel_trieda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Student', 'verbose_name_plural': 'Studenti'},
        ),
        migrations.AlterModelOptions(
            name='trieda',
            options={'ordering': ['nazov'], 'verbose_name': 'Trieda', 'verbose_name_plural': 'Triedy'},
        ),
        migrations.AlterModelOptions(
            name='ucitel',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Ucitel', 'verbose_name_plural': 'Ucitelia'},
        ),
        migrations.CreateModel(
            name='Kruzok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('skratka', models.CharField(max_length=5)),
                ('ucitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skola.ucitel')),
            ],
            options={
                'verbose_name': 'Kruzok',
                'verbose_name_plural': 'Kruzky',
                'ordering': ['nazov'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='kruzok',
            field=models.ManyToManyField(blank=True, to='skola.kruzok'),
        ),
    ]
