# Generated by Django 4.2.7 on 2024-04-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_alter_student_options_alter_trieda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='obec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='psc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='ulica',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
