# Generated by Django 4.2.7 on 2024-04-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0005_student_narodenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucitel',
            name='narodenie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='obec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='psc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='ulica',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
