# Generated by Django 4.2.7 on 2023-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nick',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
